export enum Router {
  Root = '/',
  Home = '/home',
  Dashboard = '/dashboard',
  Login = '/login',
  Register = '/register',
  Profile = '/user/my-account',
  Billing = '/user/billing',
  Settings = '/settings',
  NotFound = '/404',
  About = '/about',
  Privacy = '/privacy-policy',
  TermConditions = '/terms-and-conditions',
  HowItWorks = '/how-it-works',
  Contact = '/contact',
  ResetPassword = '/reset-password',
  VerifyRegister = '/verify-register',
  VerifyRegisterSuccess = '/verify-register-success',
  CheckYourEmail = '/check-your-email',
  AccountDeletionRequest = '/account-deletion-request',
}
